[project]
name = "sparv-statistics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["sparv-pipeline>=5.2.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
